version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore'
    cooldown:
      semver-major-days: 30
    groups:
      npm-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'ci'
    cooldown:
      semver-major-days: 30
    groups:
      github-actions:
        patterns:
          - '*'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'build'
    cooldown:
      semver-major-days: 30
    groups:
      docker:
        patterns:
          - '*'
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: 'chore'
    cooldown:
      semver-major-days: 30
    groups:
      bundler:
        patterns:
          - '*'
