- ignore:
    - vulnerability: 'GHSA-3v7f-55p6-f55p'
      package:
        name: picomatch
        type: npm
    - vulnerability: 'GHSA-c2c7-rcm5-vvqj'
      package:
        name: picomatch
        type: npm
    - vulnerability: 'CVE-2025-60876'
      package:
        name: busybox
        type: apk
    - vulnerability: 'CVE-2025-60876'
      package:
        name: busybox-binsh
        type: apk
    - vulnerability: 'CVE-2025-60876'
      package:
        name: ssl_client
        type: apk
    - vulnerability: 'GHSA-f886-m6hf-6m8v'
      package:
        name: brace-expansion
        type: npm
