version: '3.5'

services:
  gotreasa-berlin-clock:
    image: gotreasa-berlin-clock
    container_name: gotreasa-berlin-clock
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/src
      - goss:/goss:ro
    environment:
      NODE_ENV: production
    ports:
      - 9080:9080
    restart: always
    healthcheck:
      test: ['CMD', '/goss/goss', 'validate']
      interval: 10s
      timeout: 10m
      retries: 5
      start_period: 30s
  goss:
    image: aelsabbahy/goss
    container_name: goss
    volumes:
      - goss:/goss:ro

volumes:
  goss:
