version: '3.5'

services:
  gotreasa-berlin-clock:
    image: gotreasa-berlin-clock
    container_name: gotreasa-berlin-clock
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9080:9080
